name: Run examples

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:

jobs:
  examples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version:
          - '1.7.0-rc1'
      fail-fast: false
    name: Examples Julia ${{ matrix.julia-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - run: make -C examples
